/** Acciones del workflow. Espejo del enum de Prisma, pero independiente. */
export enum AccionMovimiento {
  CREAR = 'CREAR',
  INGRESAR = 'INGRESAR',
  TOMAR = 'TOMAR',
  ASIGNAR = 'ASIGNAR',
  DERIVAR = 'DERIVAR',
  OBSERVAR = 'OBSERVAR',
  RESPONDER_OBSERVACION = 'RESPONDER_OBSERVACION',
  SOLICITAR_INTERVENCION_EXTERNA = 'SOLICITAR_INTERVENCION_EXTERNA',
  RESPONDER_INTERVENCION_EXTERNA = 'RESPONDER_INTERVENCION_EXTERNA',
  APROBAR = 'APROBAR',
  RECHAZAR = 'RECHAZAR',
  CANCELAR = 'CANCELAR',
  CERRAR = 'CERRAR',
}
